services:

  redis:
    image: redis:7-bookworm
    container_name: redis
    restart: always
    volumes:
    - ./dataredis:/data
    - ./dataredis/redis.conf:/data/redis.conf
    command: redis-server /data/redis.conf --loglevel notice --requirepass ${REDIS_PASSWORD}
    networks:
      - mired
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.redis.rule=HostSNI(`*`)"
      - "traefik.tcp.services.redis.loadbalancer.server.port=6379"
    
networks:
  mired:
      external: true