version: '1.0'
services:
    mysql:
        #container_name: mysql
        image: mysql:8.0.36-debian

        command: --default-authentication-plugin=mysql_native_password

        networks: 
            - redinterna
        ports:
            - "3306:3306"
        environment:
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            - ./data:/var/lib/mysql
        restart: always
networks:
    redinterna:
